-- AlterTable
ALTER TABLE "bloodCenter" ADD COLUMN     "signUpDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "guadian" ADD COLUMN     "signUpDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
